---

    - name: Add permissions to the admin.conf file
      when: master is defined and master == 'master01'
      shell: "sudo chmod +r /etc/kubernetes/admin.conf"

    - name: run nginx container
      when: master is defined and master == 'master01'
      become: yes
      shell: "docker run -d --name nginx -p 65000:80 nginx"

    - name: cp admin.conf to nginx container
      when: master is defined and master == 'master01'
      become: yes
      shell: "docker cp /etc/kubernetes/admin.conf nginx:/usr/share/nginx/html/admin.conf"

    - name: Downloading admin.conf
      when: master is defined
      shell: "curl -O {{master_01}}:65000/admin.conf"

    - name: remove nginx container
      become: yes
      shell: "docker rm nginx --force"
      ignore_errors: yes

    - name: Create kubectl config dir
      when: master is defined
      shell: "mkdir ~/.kube"
      ignore_errors: yes

    - name: Move the config file to the config directory
      when: master is defined
      become: yes
      shell: |
          mv admin.conf /home/{{ssh_user}}/.kube/config &&
          chmod 600 /home/{{ssh_user}}/.kube/config

