---

    - name: Installing helm
      when: master is defined and master == 'master01'
      shell: |
          cd /tmp &&
          wget https://storage.googleapis.com/kubernetes-helm/helm-v2.11.0-linux-amd64.tar.gz &&
          tar -xzvf helm-v2.11.0-linux-amd64.tar.gz &&
          sudo mv linux-amd64/helm /usr/local/bin/helm

    - name: Cloning kubernetes-course repo and runnig helm
      when: master is defined and master == 'master01'
      shell: |
          cd /tmp &&
          git clone https://github.com/wardviaene/kubernetes-course.git &&
          cd kubernetes-course/helm/ &&
          kubectl create -f helm-rbac.yaml &&
          helm init --service-account tiller

